### numpy 파이썬의 구세주!

[넘파이홈페이지](https://numpy.org/) 
<img src="https://numpy.org/images/logo.svg" width="50px">

연산을 위한 기초 패키지로, 배열의 빠른 작업을 제공해주는 파이썬 라이브러리



In [ ]:
#주피터 노트에서의 쉘 명령
# %를 붙여주세요. 터미널에서는 빼 주세요~ 

%pip install numpy
# !pip install numpy


In [ ]:
import numpy as np
# 넘파이 vs 파이썬 리스트 속도비교
nparray = np.arange(1000000)
pylist = list(range(1000000))

%time for _ in range(10): np_array2 = nparray*2
%time for _ in range(10): pylist2 = [x*2 for x in pylist]

In [ ]:
import numpy as np # numpy는 일반적으로 np로 축약해서 사용

a = np.arange(15)
%pinfo a
#타입은 ndarray (n차원의 배열)

In [ ]:
a = a.reshape(3,5)
print(a)
print(type(a))
a.ndim, a.shape,a.size, a.dtype, a.dtype.name, a.itemsize, a.data

In [29]:
#np array 생성
# 파이썬 리스트(튜플)사용
a = np.array([2,3,4])
b = np.array((2,3,4))
a,b

(array([2, 3, 4]), array([2, 3, 4]))

In [35]:
# n개의 축을 생성하는 경우
a = np.array(([1,2,3],[4,5,6]))
b = np.array(((1,2,3),(4,5,6)))
a, b, a.shape, b.shape

(array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), (2, 3), (2, 3))

In [39]:
# 다만 인수는 모든 타입이 동일해야 한다!
a = np.array((1, 2, 3.5))
b = np.array((1,2.5, "파이썬"))
a, b

(array([1. , 2. , 3.5]), array(['1', '2.5', '파이썬'], dtype='<U32'))

In [50]:
# 데이터 타입을 명시해서 생성
a = np.array(((1,2,3),(4,5,6)), dtype=np.float32)
b = np.array(((1,2,3,),(4,5,6.,))) #단일 타입이어야 함. 따라서 모든 원소를 포함할 수 있는 타입으로 자동 캐스팅
c = np.array((1.2j))
a, b, c, b.dtype, c.dtype

(array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32), array([[1., 2., 3.],
       [4., 5., 6.]]), array(0.+1.2j), dtype('float64'), dtype('complex128'))

In [69]:
# np array 생성 2

#0으로 가득찬 배열
# shape을 전달, dtype을 전달(생략가능)
a = np.zeros((1,2))

# 1로 가득찬 배열을 생성
b = np.ones((2,3,4), dtype=np.float64)

# 아무것도 없는(?) 배열(해보면 이상한...)
c = np.empty((2,3), dtype="int64")
a, b, c


(array([[0., 0.]]), array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]]), array([[4607182418800017408, 4611686018427387904, 4613937818241073152],
       [4616189618054758400, 4617315517961601024, 4618441417868443648]],
      dtype=int64))

In [70]:
#np empty의 요상함???
a = np.empty(0)
a

array([], dtype=float64)

In [81]:
# 숫자 시퀀스를 생성
# 파이썬 리스트의 start:end:step 과 같음
a = np.arange(10)
b = np.arange(10, 30, 5)
c = np.arange(0, 2, .3)
d = np.arange(30, 10, -5)
a,b,c,d

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 15, 20, 25]), array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8]), array([30, 25, 20, 15]))

In [79]:
#원하는 요소 수를 지정
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [85]:
# array shape을 수정
a = np.arange(16).reshape(4,4)
# np.arange(12).reshape(4,4) #12개의 요소를 4x4로 만들 수 없음으로 에러

#타입을 변경
a.astype("float64")

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [93]:
#산술 연산
#파이썬의 리스트의 + 연산은 리스트의 병합
print([1,2,3,4]+[5,6,7,8])

#ndarray 연산
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b, a-b, a*b, a/b, sep="\n")
print(a**2)
print(np.sin(a))
print(b>5)

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[False  True  True  True]


In [103]:
a = np.array([
    [1,1],
    [0,1]])
b = np.array([
    [2,0],
    [3,4]])

print(a.dot(b),b.dot(a),np.dot(a,b),np.dot(b,a), a@b, a*b,sep="\n")


[[5 4]
 [3 4]]
[[2 2]
 [3 7]]
[[5 4]
 [3 4]]
[[2 2]
 [3 7]]
[[5 4]
 [3 4]]
[[2 0]
 [0 4]]


In [114]:
# 기타 연산함수
a = np.arange(5)
print(a)
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a), np.min(a))
print(np.std(a))
print(np.sum(a))
print(np.argmax(a))
print(np.average(a))
print(np.half(a))

[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         1.         1.41421356 1.73205081 2.        ]
4 0
1.4142135623730951
10
4
2.0
[0. 1. 2. 3. 4.]
[  0.          57.29577951 114.59155903 171.88733854 229.18311805]


In [ ]:
# 인덱싱과 슬라이싱
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:3])
a[:6:2] =1000
print(a)

In [163]:
# 다차원 배열에서의 인덱싱과 슬라이싱
a = np.arange(2*3*4).reshape(2,3,4)
print(a)
# print(a[:,2::-1,:])
print(a[:,:,(1,0,3,2)])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 1  0  3  2]
  [ 5  4  7  6]
  [ 9  8 11 10]]

 [[13 12 15 14]
  [17 16 19 18]
  [21 20 23 22]]]


In [ ]:
c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)
c[1,...]

In [171]:
# 복사는 항상 조심하자
a = np.arange(12).reshape(3,4)
b = a
print(b is a)
print(id(b), id(a))
a[:,(0)]=100
print(a,b,sep="\n")


True
2524930098064 2524930098064
[[100   1   2   3]
 [100   5   6   7]
 [100   9  10  11]]
[[100   1   2   3]
 [100   5   6   7]
 [100   9  10  11]]


In [173]:
#파이썬 리스트의 깊은 복사
l = [1,2,3,4] 
l2 = l
l[0] = 100
print(l, l2)
l = [1,2,3,4] 
l2 = l[:]
l[0] = 100
print(l, l2)

[100, 2, 3, 4] [100, 2, 3, 4]
[100, 2, 3, 4] [1, 2, 3, 4]


In [178]:
# 넘파이에서는 슬라이싱 된 배열도 결국은 얕은 복사
a = np.arange(12).reshape(3,4)
b = a[:,1:3]
b[:] = 100
print(b,"\n", a)
a = np.arange(12).reshape(3,4)
b = a[:,1:3].copy()
b[:] = 100
print(b,"\n", a)

[[100 100]
 [100 100]
 [100 100]] 
 [[  0 100 100   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[100 100]
 [100 100]
 [100 100]] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [115]:
#파일로 저장
a = np.array([1,2,3,4,5])
np.save("test",a)
#test.npy파일이 저장 (이진파일이라 text로 읽을 수 없음)

In [118]:
#저장할 때에는 확장자를 생략할 수 있지만
#로드에서는 확장자를 붙여야만 한다.
a = np.load("test.npy")
print(a)

[1 2 3 4 5]


In [123]:
#text 파일을 이용
a = np.array([[1,2,3,4],[5,6,7,8]])
np.savetxt("test.txt", a)

In [125]:
#text 파일 불러오기
a = np.loadtxt("test.txt")
a

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [126]:
# csv 파일 다루기
# csv는 별다른 것 없이 delimiter를 지정
np.savetxt("text.csv",a,delimiter=",")

In [127]:
np.loadtxt("text.csv",delimiter=",")

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])